services:
  keycloak:
    image: 'quay.io/keycloak/keycloak:24.0'
    ports:
      - "8180:8080"
    environment:
      - TZ=Europe/Madrid
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=mariadb
      - KC_DB_URL=jdbc:mariadb://mariadb:3306/keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=password
      - KC_FEATURES=preview
    volumes:
      - ./kc_data:/opt/keycloak/data
      - ./plugins/authdelay.jar:/opt/keycloak/providers/authdelay.jar
    depends_on:
        - mariadb
    command:
      - start-dev
  mariadb:
      image: mariadb
      volumes:
        - data:/var/lib/mysql
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: keycloak
        MYSQL_USER: keycloak
        MYSQL_PASSWORD: password
      healthcheck:
        test: ["CMD", "mysqladmin", "ping", "--silent"]
volumes:
  data:
    driver: local